// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

namespace Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200131050630_SeedUsers")]
    partial class SeedUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Domain.UserTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserTables");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "josh@life.com",
                            UserName = "Josh"
                        },
                        new
                        {
                            Id = 2,
                            Email = "josasdfasdfh@life.com",
                            UserName = "Joshua"
                        },
                        new
                        {
                            Id = 3,
                            Email = "joasdfsh@life.com",
                            UserName = "Joshie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
