// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

namespace Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200331015836_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Domain.Game", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameName")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            GameId = new Guid("899f04dd-064d-477a-a45d-e6b9a03aa970"),
                            GameName = "Goblin Battle",
                            UserId = 10220438528782809L
                        },
                        new
                        {
                            GameId = new Guid("5eb46df3-a99d-4ecb-b88d-71becf1bc026"),
                            GameName = "Orc Battle",
                            UserId = 10220438528782809L
                        },
                        new
                        {
                            GameId = new Guid("a5310bf9-b45c-41b7-b732-2122245122e6"),
                            GameName = "Dragon Battle",
                            UserId = 20220438528782809L
                        },
                        new
                        {
                            GameId = new Guid("2fc4493f-bc85-40c1-a82a-7fcd02d03b29"),
                            GameName = "Minotaur Battle",
                            UserId = 30220438528782809L
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 10220438528782809L,
                            UserName = "Josh Wren"
                        },
                        new
                        {
                            Id = 20220438528782809L,
                            UserName = "Tim"
                        },
                        new
                        {
                            Id = 30220438528782809L,
                            UserName = "Bob"
                        });
                });

            modelBuilder.Entity("Domain.Game", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany("Games")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
