// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistance;

namespace Persistance.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Domain.Game", b =>
                {
                    b.Property<long>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("GameName")
                        .HasColumnType("TEXT");

                    b.Property<long>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId");

                    b.HasIndex("UserId");

                    b.ToTable("Game");

                    b.HasData(
                        new
                        {
                            GameId = 40220438528782809L,
                            GameName = "Goblin Battle",
                            UserId = 10220438528782809L
                        },
                        new
                        {
                            GameId = 50220438528782809L,
                            GameName = "Orc Battle",
                            UserId = 10220438528782809L
                        },
                        new
                        {
                            GameId = 60220438528782809L,
                            GameName = "Dragon Battle",
                            UserId = 20220438528782809L
                        },
                        new
                        {
                            GameId = 70220438528782809L,
                            GameName = "Minotaur Battle",
                            UserId = 30220438528782809L
                        });
                });

            modelBuilder.Entity("Domain.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 10220438528782809L,
                            UserName = "Josh Wren"
                        },
                        new
                        {
                            Id = 20220438528782809L,
                            UserName = "Tim"
                        },
                        new
                        {
                            Id = 30220438528782809L,
                            UserName = "Bob"
                        });
                });

            modelBuilder.Entity("Domain.Game", b =>
                {
                    b.HasOne("Domain.User", "User")
                        .WithMany("Games")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
